// templates/next-app/src/app/page.tsx
"use client";
import { useLaserEyes } from "@omnisat/lasereyes";
import { ConnectWallet } from "@/components/ConnectWallet";

export default function Home() {
  const { address } = useLaserEyes();

  return (
    <div className="min-h-screen flex flex-col items-center justify-center gap-8 p-8">
      <h1 className="text-4xl font-bold text-center">
        Welcome to LaserEyes Template
      </h1>
      <div className="flex flex-col items-center gap-4">
        <ConnectWallet />
        {address && (
          <div className="flex flex-col gap-2">
            <p className="text-lg text-center">Connected Address: {address}</p>
          </div>
        )}
      </div>
    </div>
  );
}

// templates/vue-app/src/App.vue
<script setup lang="ts">
import { DefaultLayout } from "./components/DefaultLayout.vue";
</script>

<template>
  <DefaultLayout>
    <div
      class="min-h-screen flex flex-col items-center justify-center gap-8 p-8"
    >
      <h1 class="text-4xl font-bold text-center">
        Welcome to LaserEyes Template
      </h1>
      <div class="flex flex-col items-center gap-4">
        <ConnectWallet />
        <div v-if="address" class="flex flex-col gap-2">
          <p class="text-lg text-center">Connected Address: {{ address }}</p>
        </div>
      </div>
    </div>
  </DefaultLayout>
</template>
